const LOGIN_USER = "LOGIN_USER";
const LOGIN_ERROR = "LOGIN_ERROR";
const LOGIN_RESET = "LOGIN_RESET";
const SET_PRESENTATIONS = "SET_PRESENTATIONS";
const SET_PROJECTS = "SET_PROJECTS";
const SET_EXERCISES = "SET_EXERCISES";
const SET_HOMEWORK = "SET_HOMEWORK";
const SET_LOADING = "SET_LOADING";
const LOGOUT_USER = "LOGOUT_USER";
const LOGIN_USER_LOAD = "LOGIN_USER_LOAD";
const OPEN_UPLOAD = "OPEN_UPLOAD";
const CLOSE_UPLOAD = "CLOSE_UPLOAD";
const UPLOAD_LOADING = "UPLOAD_LOADING";
const OPEN_TUTORIAL = "OPEN_TUTORIAL";
const CLOSE_TUTORIAL = "CLOSE_TUTORIAL";
const SET_TASKS = "SET_TASKS";
const SET_TUTORIALS = "SET_TUTORIALS";
const SET_LECTURES = "SET_LECTURES";
const SET_CURRENT_TUTORIAL = "SET_CURRENT_TUTORIAL";
const SIDEBAR_OPEN = "SIDEBAR_OPEN";
const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
const CHANGE_ACTIVE_LINK = "CHANGE_ACTIVE_LINK";
const SET_SECTIONS_POSITIONS = "SET_SECTIONS_POSITIONS";
const CHECK_SECTIONS_POSITIONS = "CHECK_SECTIONS_POSITIONS";
const SHOW_CONTACT_FEEDBACK = "SHOW_CONTACT_FEEDBACK";
const CLEAR_FEEDBACK = "CLEAR_FEEDBACK";
const SET_SCROLLED_PERCENTAGE = "SET_SCROLLED_PERCENTAGE";
const LOGIN_LOADING = "LOGIN_LOADING";
const ADD_HOMEWORK = "ADD_HOMEWORK";
const SEND_EMAIL = "SEND_EMAIL";
export {
  LOGIN_LOADING,
  LOGIN_USER,
  LOGIN_ERROR,
  LOGIN_RESET,
  SET_PRESENTATIONS,
  SET_PROJECTS,
  SET_EXERCISES,
  SET_HOMEWORK,
  SET_LOADING,
  LOGOUT_USER,
  LOGIN_USER_LOAD,
  OPEN_UPLOAD,
  CLOSE_UPLOAD,
  UPLOAD_LOADING,
  OPEN_TUTORIAL,
  CLOSE_TUTORIAL,
  SET_TASKS,
  SET_TUTORIALS,
  SET_CURRENT_TUTORIAL,
  SIDEBAR_OPEN,
  SIDEBAR_CLOSE,
  CHANGE_ACTIVE_LINK,
  SET_SECTIONS_POSITIONS,
  CHECK_SECTIONS_POSITIONS,
  SHOW_CONTACT_FEEDBACK,
  CLEAR_FEEDBACK,
  SET_SCROLLED_PERCENTAGE,
  ADD_HOMEWORK,
  SEND_EMAIL,
  SET_LECTURES,
};
